name: OSS-Fuzz Emulation CI

on:
  # Manual execution option
  workflow_dispatch:

  # Trigger on push to main
  push:
    branches:
      - main

  # Scheduled daily run at 00:00 UTC
  schedule:
    - cron: '0 0 * * *'

jobs:
  fuzz:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check Docker version
      run: docker --version

    - name: Build fuzzers
      run: |
        python3 infra/helper.py build_fuzzers zlib

    - name: Run fuzzers with corpus and dump crash info
      run: |
        mkdir -p artifacts
        python3 infra/helper.py run_fuzzer zlib compress_fuzzer corpus/ || true

        echo "===== Crash files ====="
        if ls build/out/zlib/crash-* 1>/dev/null 2>&1; then
          ls -lh build/out/zlib/crash-*
          echo "===== Crash contents (base64) ====="
          for f in build/out/zlib/crash-*; do
            echo "[PoC file: $f]"
            base64 "$f" | head -n 10
            echo "---"
          done
        else
          echo "No crash files found."
        fi

    - name: Introspector build
      run: |
        python3 infra/helper.py build_fuzzers --sanitizer=introspector zlib

    - name: Run Introspector analysis (30s)
      run: |
        python3 infra/helper.py introspector zlib --seconds=30
        echo "Introspector report should be under build/out/zlib/introspector-report/inspector"
