name: OSS-Fuzz Emulation CI

on:
  # Manual execution option
  workflow_dispatch:

  # Trigger on push to main
  push:
    branches:
      - main

  # Scheduled daily run at 00:00 UTC
  schedule:
    - cron: '0 0 * * *'

jobs:
  fuzz:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check Docker version
      run: docker --version

    - name: Build fuzzers
      run: |
        python3 infra/helper.py build_fuzzers zlib

    - name: Run fuzzers and capture crash info
      run: |
        mkdir -p artifacts
        # Run fuzzer and save both stdout and stderr to log.txt
        (python3 infra/helper.py run_fuzzer zlib compress_fuzzer || true) 2>&1 | tee artifacts/log.txt

        # Copy PoC crash files if any
        if ls build/out/zlib/crash-* 1>/dev/null 2>&1; then
          cp build/out/zlib/crash-* artifacts/
        fi

        # Save the fuzzer binary too
        cp build/out/zlib/compress_fuzzer artifacts/

    - name: Upload fuzz artifacts (PoC, binary, logs)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: fuzz-repro-assets
        path: artifacts/

    - name: Build fuzzers for introspector
      run: |
        python3 infra/helper.py build_fuzzers --sanitizer=introspector zlib

    - name: Run introspector (30s)
      run: |
        python3 infra/helper.py introspector zlib --seconds=30 || true

    - name: Upload introspector report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: introspector-report
        path: build/out/zlib/introspector-report/
