name: OSS-Fuzz Emulation CI

on:
  # Manual execution option
  workflow_dispatch:

  # Trigger on push to main
  push:
    branches:
      - main

  # Scheduled daily run at 00:00 UTC
  schedule:
    - cron: '0 0 * * *'

jobs:
  fuzz:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check Docker version
      run: docker --version

    - name: Build fuzzers
      run: |
        python3 infra/helper.py build_fuzzers zlib

    - name: Run fuzzers and dump crash info
      run: |
        mkdir -p artifacts
        python3 infra/helper.py run_fuzzer zlib compress_fuzzer || true

        echo "===== Crash files ====="
        if ls build/out/zlib/crash-* 1>/dev/null 2>&1; then
          ls -lh build/out/zlib/crash-*
          echo "===== Crash contents (base64) ====="
          for f in build/out/zlib/crash-*; do
            echo "[PoC file: $f]"
            base64 "$f" | head -n 10
            echo "---"
          done
        else
          echo "No crash files found."
        fi

    - name: Dump crash PoCs as base64 .txt
      if: always()
      run: |
        mkdir -p artifacts_base64
        if ls build/out/zlib/crash-* 1>/dev/null 2>&1; then
          for f in build/out/zlib/crash-*; do
            base64 "$f" > "artifacts_base64/$(basename "$f").txt"
          done
        else
          echo "No crash files to encode."
        fi

    - name: Upload crash artifacts (raw and base64)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: fuzz-crashes
        path: |
          artifacts/
          artifacts_base64/

    - name: Build fuzzers for introspector
      run: |
        python3 infra/helper.py build_fuzzers --sanitizer=introspector zlib

    - name: Run introspector (30s)
      run: |
        python3 infra/helper.py introspector zlib --seconds=30 || true

    - name: Upload introspector report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: introspector-report
        path: build/out/zlib/introspector-report/
