name: OSS-Fuzz Emulation CI

on:
  workflow_dispatch:          # Manual trigger
  push:                       # Trigger on push to main
    branches:
      - main
  schedule:                   # Run every 5 minutes (for testing)
    - cron: '*/5 * * * *'

jobs:
  fuzz:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check Docker version
      run: docker --version

    - name: Build fuzzers
      run: |
        python3 infra/helper.py build_fuzzers zlib

    - name: Run fuzzers and dump crash info
      run: |
        mkdir -p artifacts
        python3 infra/helper.py run_fuzzer zlib compress_fuzzer || true

        echo "===== Crash files ====="
        if ls build/out/zlib/crash-* 1>/dev/null 2>&1; then
          ls -lh build/out/zlib/crash-*
          echo "===== Crash contents (base64) ====="
          for f in build/out/zlib/crash-*; do
            echo "[PoC file: $f]"
            base64 "$f" | head -n 10
            echo "---"
          done
        else
          echo "No crash files found."
        fi
